"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_yellow)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
$git_state\
[](fg:color_aqua bg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
$cmd_duration\
$jobs\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

# =============================================================================
# Theme Palettes
# =============================================================================

# 터미널 테마에 자동 적응하는 ANSI 색상 기반 팔레트
# 터미널 테마(Dracula, Gruvbox 등)가 정의한 색상을 그대로 사용합니다
[palettes.terminal_adaptive]
color_fg0 = 'white'           # 어두운 배경용 텍스트
color_fg_dark = 'black'       # 밝은 배경용 텍스트
color_bg1 = 'black'           # 가장 어두운 배경 (time)
color_bg3 = 'bright-black'    # 중간 배경 (docker, conda, cmd_duration)
color_blue = 'bright-blue'    # 언어 섹션 (밝은 파랑)
color_aqua = 'cyan'           # git 섹션
color_green = 'green'
color_orange = 'red'          # OS/username (빨강으로 시작점 강조)
color_purple = 'magenta'
color_red = 'bright-red'
color_yellow = 'yellow'       # directory 섹션

# -----------------------------------------------------------------------------
# 고정 색상 팔레트 (특정 테마를 강제로 사용하고 싶을 때)
# palette = 'gruvbox_dark' 등으로 변경하여 사용
# -----------------------------------------------------------------------------

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg_dark = '#3c3836'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.everforest]
color_fg0 = '#d3c6aa'
color_fg_dark = '#2d353b'
color_bg1 = '#343f44'
color_bg3 = '#3d484d'
color_blue = '#7fbbb3'
color_aqua = '#83c092'
color_green = '#a7c080'
color_orange = '#e69875'
color_purple = '#d699b6'
color_red = '#e67e80'
color_yellow = '#dbbc7f'

[palettes.tokyo_night]
color_fg0 = '#c0caf5'
color_fg_dark = '#1a1b26'
color_bg1 = '#24283b'
color_bg3 = '#414868'
color_blue = '#7aa2f7'
color_aqua = '#7dcfff'
color_green = '#9ece6a'
color_orange = '#ff9e64'
color_purple = '#bb9af7'
color_red = '#f7768e'
color_yellow = '#e0af68'

[palettes.catppuccin_mocha]
color_fg0 = '#cdd6f4'
color_fg_dark = '#1e1e2e'
color_bg1 = '#313244'
color_bg3 = '#45475a'
color_blue = '#89b4fa'
color_aqua = '#94e2d5'
color_green = '#a6e3a1'
color_orange = '#fab387'
color_purple = '#cba6f7'
color_red = '#f38ba8'
color_yellow = '#f9e2af'

[palettes.catppuccin_latte]
color_fg0 = '#4c4f69'
color_fg_dark = '#eff1f5'
color_bg1 = '#ccd0da'
color_bg3 = '#bcc0cc'
color_blue = '#1e66f5'
color_aqua = '#179299'
color_green = '#40a02b'
color_orange = '#fe640b'
color_purple = '#8839ef'
color_red = '#d20f39'
color_yellow = '#df8e1d'

[palettes.nord]
color_fg0 = '#eceff4'
color_fg_dark = '#2e3440'
color_bg1 = '#434c5e'
color_bg3 = '#4c566a'
color_blue = '#5e81ac'
color_aqua = '#88c0d0'
color_green = '#a3be8c'
color_orange = '#d08770'
color_purple = '#b48ead'
color_red = '#bf616a'
color_yellow = '#ebcb8b'

[palettes.dracula]
color_fg0 = '#f8f8f2'
color_fg_dark = '#282a36'
color_bg1 = '#44475a'
color_bg3 = '#6272a4'
color_blue = '#bd93f9'
color_aqua = '#8be9fd'
color_green = '#50fa7b'
color_orange = '#ffb86c'
color_purple = '#ff79c6'
color_red = '#ff5555'
color_yellow = '#f1fa8c'

[palettes.rose_pine]
color_fg0 = '#e0def4'
color_fg_dark = '#191724'
color_bg1 = '#26233a'
color_bg3 = '#6e6a86'
color_blue = '#31748f'
color_aqua = '#9ccfd8'
color_green = '#9ccfd8'
color_orange = '#ebbcba'
color_purple = '#c4a7e7'
color_red = '#eb6f92'
color_yellow = '#f6c177'

[palettes.one_dark]
color_fg0 = '#abb2bf'
color_fg_dark = '#282c34'
color_bg1 = '#2c323c'
color_bg3 = '#3e4452'
color_blue = '#61afef'
color_aqua = '#56b6c2'
color_green = '#98c379'
color_orange = '#d19a66'
color_purple = '#c678dd'
color_red = '#e06c75'
color_yellow = '#e5c07b'

[palettes.solarized_dark]
color_fg0 = '#fdf6e3'
color_fg_dark = '#002b36'
color_bg1 = '#073642'
color_bg3 = '#586e75'
color_blue = '#268bd2'
color_aqua = '#2aa198'
color_green = '#859900'
color_orange = '#cb4b16'
color_purple = '#6c71c4'
color_red = '#dc322f'
color_yellow = '#b58900'

[palettes.kanagawa]
color_fg0 = '#dcd7ba'
color_fg_dark = '#1f1f28'
color_bg1 = '#2a2a37'
color_bg3 = '#363646'
color_blue = '#7e9cd8'
color_aqua = '#6a9589'
color_green = '#76946a'
color_orange = '#ffa066'
color_purple = '#957fb8'
color_red = '#c34043'
color_yellow = '#c0a36e'

[palettes.gruvbox_material]
color_fg0 = '#d4be98'
color_fg_dark = '#282828'
color_bg1 = '#32302f'
color_bg3 = '#45403d'
color_blue = '#7daea3'
color_aqua = '#89b482'
color_green = '#a9b665'
color_orange = '#e78a4e'
color_purple = '#d3869b'
color_red = '#ea6962'
color_yellow = '#d8a657'

[os]
disabled = true
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = false
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg_dark bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"SynologyDrive/_devspace" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg_dark bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg_dark bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
disabled = true
# uv 주력 사용 → custom.uv_python으로 대체
[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_aqua bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_aqua bg:color_bg3)]($style)'

[custom.uv_python]
command = 'uv python find --show-version 2>/dev/null'
style = "bg:color_bg3"
format = '[[ $symbol( $output) ](fg:color_aqua bg:color_bg3)]($style)'
symbol = " uv"
detect_extensions = ['py', 'ipynb']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini', 'uv.lock', 'pylock.toml']

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[cmd_duration]
min_time = 2000
show_milliseconds = false
style = "bg:color_bg3"
format = '[[  $duration ](fg:color_yellow bg:color_bg3)]($style)'

[jobs]
symbol = "+"
style = "bg:color_bg3"
format = '[[ $symbol$number ](fg:color_purple bg:color_bg3)]($style)'

[git_state]
style = "bg:color_aqua"
format = '[[ $state( $progress_current/$progress_total) ](fg:color_fg_dark bg:color_aqua)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
